# T-Pot (Sensor)
# Do not erase ports sections, these are used by /opt/tpot/bin/rules.sh to setup iptables ACCEPT rules for NFQ (honeytrap / glutton)
version: '2.3'

#networks:
 # adbhoney_local:
 # ciscoasa_local:
 # citrixhoneypot_local:
 # conpot_local_IEC104:
 # conpot_local_guardian_ast:
 # conpot_local_ipmi:
 # conpot_local_kamstrup_382:
 # cowrie_local:
 # ddospot_local:
 # dicompot_local:
 # dionaea_local:
 # elasticpot_local:
 # heralding_local:
 # ipphoney_local:
 # mailoney_local:
 # medpot_local:
 # redishoneypot_local:
 # tanner_local:
 # ewsposter_local:
 # sentrypeer_local:
 # spiderfoot_local:

services:

##################
#### Honeypots
##################

# Suricata service
  suricata:
    container_name: suricata
    restart: always
    environment:
    # For ET Pro ruleset replace "OPEN" with your OINKCODE
     - OINKCODE=OPEN
    # Loading externel Rules from URL 
    # - FROMURL="https://username:password@yoururl.com|https://username:password@otherurl.com"
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    image: "dtagdevsec/suricata:2204"
    volumes:
     - /data/suricata/log:/var/log/suricata


##################
#### Tools
##################

# Ewsposter service
 # ewsposter:
 #   container_name: ewsposter
 #   restart: always
 #   networks:
 #    - ewsposter_local
 #   environment:
 #    - EWS_HPFEEDS_ENABLE=false
 #    - EWS_HPFEEDS_HOST=host
 #    - EWS_HPFEEDS_PORT=port
 #    - EWS_HPFEEDS_CHANNELS=channels
 #    - EWS_HPFEEDS_IDENT=user
 #    - EWS_HPFEEDS_SECRET=secret
 #    - EWS_HPFEEDS_TLSCERT=false
 #    - EWS_HPFEEDS_FORMAT=json
 #   env_file:
 #    - /opt/tpot/etc/compose/elk_environment
 #   image: "dtagdevsec/ewsposter:2204"
 #   volumes:
 #    - /data:/data
 #    - /data/ews/conf/ews.ip:/opt/ewsposter/ews.ip
